Add graph PS #5547
boostcamp-ai-tech-4/coding-test-study pull request #19
Opened 2021-05-15 10:41 UTC by bsm8734

### 📌 푼 문제들

- [16918_봄버맨](https://www.acmicpc.net/problem/16918)
- [5547_일루미나티](https://www.acmicpc.net/problem/5547)

---

### 📝 간단한 풀이 과정

#### 16918_봄버맨

- 규칙성을 찾아야함
- N을 `(시간)초` 라고 할 때, 시간에 따른 규칙성을 찾아서 BFS를 진행
- 규칙
  1. `N==1`의 경우, 초기상태를 그대로 출력
  2. `N%2 == 0`의 경우, 모든 위치에 폭탄이 설치되어 있으므로, 모두 0으로 채워진 배열을 출력
  3. `N%4 == 3`의 경우, 초기에 설치되었던 폭탄이 주위를 depth=1로 터뜨린 결과를 출력
  4. `N%4 == 1`의 경우, 3번 경우를 한 번 수행하고도 터지지 않은 폭탄의 위치를 수집하여, 모든 map의 인자를 o으로 만든 다음, 수집한 폭탄으로부터 depth=1로 폭탄을 터뜨린 결과를 출력함 (3번을 2번 시행한 것과 같음)

#### 5547_일루미나티

> ( 주의! ) 건물을 기준으로 BFS를 하면, 내부에 세면안되는 길이도 함께 카운팅되므로, 건물이 없는 곳을 기준으로 BFS 진행

- 입력을 받을때, map을 0으로 둘러쌓기(padding)
- map[0][0]을 queue에 push하고, 방문했다는 표시를 해둠
- 큐에서 하나씩 꺼내는데, 각 행이 어긋나있으므로, 하나의 건물 위치에서 `둘러쌓인 건물을 찾기위해 사용되는 배열(크기:6)`도 두 종류가 있어야함
- 건물이 없는 (0, 0)에서 시작하여 탐색을 하되, 큐에서 제거되는 때에 본인을 둘러싼 위치(6)를 보고, 건물이 있으면 건물의 수에 따라 result 변수의 값을 1 올려줌
- BFS 탐색을 완료하면, 정답을 얻을 수 있음

---

2021-05-15 14:48 UTC, CoodingPenguin reviewed
봄버맨 코드가 빠졌습니다!

2021-05-15 14:48 UTC, CoodingPenguin commented on sally/graph_traversal/5547_일루미나티.cpp
> +            cin >> a;
C++은 입력시에 알아서 split을 해주나요? 신기하네용😆

2021-05-15 14:48 UTC, CoodingPenguin commented on sally/graph_traversal/5547_일루미나티.cpp
> +        }
이 부분 코드가 꽤 중복되는데 위의 for문과 아래 for문의 차이를 설명해주실 수 있을까요?

2021-05-15 16:13 UTC, bsm8734 commented on sally/graph_traversal/5547_일루미나티.cpp
> +            cin >> a;
공백이나 줄바꿈문자 기준으로 잘려서 들어갑니당!

2021-05-15 16:16 UTC, bsm8734 commented on sally/graph_traversal/5547_일루미나티.cpp
> +        }
위 for문의 의도는 queue에서 pop하면서 해당 위치에 인접한 건물의 수를 카운팅하는 것이었고, 아래 for문은 다음 방문할 노드(건물이 없는 지역)를 탐색하기 위함이었습니다! 근데 두 구조가 완전히 동일해서 한번에 해줘도 될 것 같습니다! 조언 감사합니다! 모르고 지나갈 뻔 했네요!! ><

2021-05-16 05:19 UTC, CoodingPenguin commented
@bsm8734 봄버맨 코드가 없습니다!

2021-05-16 08:41 UTC, changwoomon approved these changes
일루미나티 ㅋㅋㅋㅋㅋ
파일 이름하고 PR Conversation에 문제이름 잘못됐어요 ㅋㅎㅋ
고생 많으셨습니다~! 🐤

2021-05-16 09:05 UTC, opijae commented on sally/graph_traversal/5547_일루미나티.cpp
> +                }
반복문을 두개로 따로 나누신 이유가 있으신가요?

2021-05-16 09:05 UTC, opijae approved these changes
고생하셨습니다!

2021-05-16 09:18 UTC, opijae commented on sally/graph_traversal/5547_일루미나티.cpp
> +                }
아 보니까 펭귄님 코멘트랑 똑같네여

2021-05-16 11:23 UTC, CoodingPenguin requested changes
@bsm8734 봄버맨 코드가 없습니다!

2021-05-16 11:38 UTC, opijae commented
> @bsm8734 봄버맨 코드가 없습니다!

헐 맞네요..

2021-05-16 15:03 UTC, CoodingPenguin approved these changes

2021-05-16 15:04 UTC, merged