[구너] 2021.07.12
boostcamp-ai-tech-4/coding-test-study pull request #202
Opened 2021-07-12 17:46 UTC by osmosm7

### 📌 푼 문제들

- [명제 증명](https://www.acmicpc.net/problem/2224)
- [끝나지 않는 파티](https://www.acmicpc.net/problem/11265)

---

### 📝 간단한 풀이 과정

#### 문제 1

> `시간복잡도`: 
플로이드 와샬을 썼으니 N^3이 아닐까요??

- chr과 ord를 새로 배웠다.

- ord를 이용해 입력 알파벳을 인코딩
- 플로이드 와샬로 명제 증명 가능한지 갱신
- 증명 가능하면 chr을 이용해 디코딩 후 출력

#### 끝나지 않는 파티

> `시간복잡도`: 
플로이드 와샬을 썼으니 N^3이 아닐까요??

- 풀이과정
- 플로이드 와샬로 최단 시간 갱신
- 최단시간 안에 도착할 수 없으면 stay here 있으면 Enjoy other party 출력
---

2021-07-12 17:51 UTC, CoodingPenguin requested changes
빈 파일이 올라왔습니다!

2021-07-13 05:32 UTC, osmosm7 commented
> 빈 파일이 올라왔습니다!

수정했습니다!

2021-07-13 12:07 UTC, dkswndms4782 approved these changes
수고하셨습니다!

2021-07-13 12:09 UTC, bsm8734 approved these changes
수고하셨습니다!

2021-07-13 12:43 UTC, opijae approved these changes
고생하셨습니다!

2021-07-13 13:48 UTC, CoodingPenguin approved these changes
수고하셨습니다!

2021-07-13 13:49 UTC, merged