[후미] 2021.07.22
boostcamp-ai-tech-4/coding-test-study pull request #241
Opened 2021-07-22 14:09 UTC by opijae

### 📌 푼 문제들

- [기차가어둠을헤치고은하수를](https://www.acmicpc.net/problem/15787)
- [배열돌리기](https://www.acmicpc.net/problem/17276)

---

### 📝 간단한 풀이 과정

#### 기차가어둠을헤치고은하수를

> `시간복잡도`: o(m*n(insert))

- 문제 해석이 어려웠다..
- 나머진 입력에 맞게 조건을 달아 주면된다.
- 다른 분 풀이보니 비트 연산을 쓰시는데 다음엔 비트로 해보자

#### 배열돌리기
> `시간복잡도`: o(3/2 n)

- 한 껍데기(???) 마다 특정 8개의 위치를 고려해 주면된다.
- 각 껍데기 마다 돌린 다음 원 배열에 적용시킨다.
- 다른분 풀이보니 deque에 rotate라는 함수를 사용하면 더 쉽게 구현할 수 있을거 같다.
---

2021-07-22 23:35 UTC, osmosm7 approved these changes

2021-07-23 03:43 UTC, changwoomon requested changes
고생하셨습니다!

2021-07-23 06:41 UTC, peacecheejecake approved these changes
고생하셨습니다!

2021-07-23 06:41 UTC, peacecheejecake commented on opijae/implementation/15787_기차가어둠을헤치고은하수를.py
> +        train[order[1]].append(0)
후미님 풀이 보고 생각난건데 여기서도 deque.rotate 써서 풀어도 되겠네요!

2021-07-23 07:23 UTC, changwoomon approved these changes

2021-07-23 07:24 UTC, merged