[펭귄] 2021.05.11
boostcamp-ai-tech-4/coding-test-study pull request #6
Opened 2021-05-11 16:44 UTC by CoodingPenguin

### 📌 푼 문제들

- [트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
- [효율적인 해킹](https://www.acmicpc.net/problem/)

---

### 📝 간단한 풀이 과정

#### 트리의 부모 찾기

- graph(연결리스트), visited(방문 여부) 외에 노드의 부모를 저장할 수 있는 부모테이블 `parent`를 생성한다.
   - `parent`의 인덱스는 노드, 값은 노드의 부모를 나타낸다.
   - 처음에는 다 자기자신으로 초기화한다.
- BFS시 visited를 갱신하고 queue에 방문하지 않는 노드 i를 넣어줄 때의 부분에 i의 부모를 큐에서 pop한 노드로 설정한다.

#### 효율적인 해킹

- 시작노드 1부터 시작해 n까지 다음을 반복한다.
    - 방문한 노드를 카운트하는 `count` 변수를 선언하고 1로 초기화한다.
    - BFS를 하면서 방문하지 않은 노드를 만났을 때 `count`를 +1 증가시킨다.
    - BFS가 끝나면 `count`를 반환한다.
- i를 시작 노드로 뒀을 때의 `count`값이 최대값과 같으면 `result`에 넣어주고, 크면 최대값을 갱신하고 `result`를 i를 넣은 리스트로 초기화시킨다.
- result를 출력한다.
    - 우연히 블로그에서 본 건데 join과 map을 사용하지 않고 `*`로 리스트를 한꺼풀 벗겨내는 연산을 적용해도 되네요. 

---

### 🙌 궁금한 점

- 효율적인 해킹 문제를 Python3로 풀 수 있는 방법이 있는 것 같은데, 어떻게 풀어야 할까요? 제 생각으로는 DP처럼 푸는 방법을 생각해봤는데.. 이게 될려면 리프 노드부터 루트 노드로 가는 패스(path)가 필요한데 더 시간이 걸릴 것 같다는 생각이 드네요ㅠㅠ

---

2021-05-11 18:39 UTC, changwoomon approved these changes
고생 많으셨습니다~! 🐧

2021-05-11 18:39 UTC, changwoomon commented on coodingpenguin/graph_traversal/1325_효율적인해킹.py
> +print(*result)
* 붙이는거 되게 신기하네용
오늘도 배워갑니다

2021-05-11 18:39 UTC, changwoomon commented on coodingpenguin/graph_traversal/11725_트리의부모찾기.py
> +graph = defaultdict(list)  # 연결 리스트
`defaultdict`를 쓰신 특별한 이유가 있으신가용
리스트로 만들어줄때보다 메모리를 적게 먹나요?

2021-05-11 19:08 UTC, opijae requested changes
효율적인 해킹에 하이퍼링크가 제대로 안달려있습니다!

2021-05-11 19:09 UTC, opijae commented on coodingpenguin/graph_traversal/11725_트리의부모찾기.py
> +parent = list(range(n + 1))  # 부모테이블
이게 되네요...

2021-05-11 19:10 UTC, opijae commented
고생하셨습니다.

2021-05-11 21:22 UTC, bsm8734 commented on coodingpenguin/graph_traversal/1325_효율적인해킹.py
> +print(*result)
그러게요 * 붙이는거 처음봤어요! 신기..!

2021-05-11 21:22 UTC, bsm8734 approved these changes
고생하셨습니다~!!

2021-05-12 03:03 UTC, CoodingPenguin commented on coodingpenguin/graph_traversal/11725_트리의부모찾기.py
> +graph = defaultdict(list)  # 연결 리스트
넵! 리스트로 만들어주게 되면 n의 개수만큼의 리스트 안에 리스트를 만들어줘야 하는데 빈 리스트여도 어느 정도 자리를 차지하게 됩니다. 하지만 `defaultdict`로 만들어주면 간선이 있을 때만 저장이 되니 리스트보다 메모리를 적게 씁니다.

다른 것보다 `defaultdict`로 해주면 알아서 빈 리스트를 생성해주고 노드가 1부터 시작할 때 인덱스랑 맞춰주려고 n+1만큼 빈 리스트를 만들어주지 않아도 되서 사용합니다!

2021-05-12 03:05 UTC, opijae approved these changes

2021-05-12 03:05 UTC, merged

2021-05-12 04:12 UTC, changwoomon commented on coodingpenguin/graph_traversal/11725_트리의부모찾기.py
> +graph = defaultdict(list)  # 연결 리스트
꿀팁이네요.. 답변 감사합니다!!