[구너] 2021.06.17
boostcamp-ai-tech-4/coding-test-study pull request #87
Opened 2021-06-17 14:49 UTC by osmosm7

### 📌 푼 문제들

- [단절점과단절선](https://www.acmicpc.net/problem/14675)

---

### 📝 간단한 풀이 과정

#### 단절점과 단절선

- 풀이과정
- 1. 단절선에 대한 질문은 무조건 yes였다.
- 2. 각 노드들의 연결 edge 수를 나타내는 모두 0인 list 생성
- 3. 엣지에 대한 정보를 받으면 엣지에 포함된 node의 위치의 list를 1씩 더해줌
- 4. 단절점에 대한 질문을 받으면 노드에 연결된 엣지 수가 2개 이상이면 yes 아니면 no 출력

---

### 🙌 궁금한 점

- 그래프내의 단절점을 모두 찾는 '단절점'(11266) 문제는 플래티넘5 난이도 추후에 도전하자!

- sys.stdin.readline() 을 이용해 input을 받지 않으면 시간초과가 뜬다. - 지금까지 몰랐음
---

2021-06-17 19:16 UTC, opijae requested changes
파일이 안보야요.....

2021-06-18 08:12 UTC, osmosm7 commented
어제 파일 안올라가서 다시 올렷습니다!

2021-06-18 10:16 UTC, changwoomon approved these changes
고생하셨습니다~! 💣

2021-06-18 16:25 UTC, opijae approved these changes
고생하셨습니다!

2021-06-18 16:48 UTC, CoodingPenguin approved these changes
수고하셨습니다!

2021-06-19 08:18 UTC, bsm8734 approved these changes
수고하셨습니다! :)

2021-06-20 03:28 UTC, peacecheejecake approved these changes
고생하셨습니다!

2021-06-20 09:33 UTC, merged